In [1]:
import pandas as pd 
import  seaborn as sns 

titanic = sns.load_dataset("titanic")

In [3]:
(titanic["age"] < 18).sum()

np.int64(113)

moins de 18 ans : 133

In [ ]:

titanic.nlargest(5, "fare")[["fare", "class"]]

#billet plus cher : 512.33

         fare  class
258  512.3292  First
679  512.3292  First
737  512.3292  First
27   263.0000  First
88   263.0000  First

In [ ]:
 
titanic.groupby("sex")["survived"].mean() * 100

sex
female    74.203822
male      18.890815
Name: survived, dtype: float64

In [8]:

femmes = titanic[(titanic["sex"] == "female") & (titanic["class"] == "First")]
print("Femmes de 1re classe :", femmes["survived"].mean() * 100, "%")


hommes = titanic[(titanic["sex"] == "male") & (titanic["class"] == "Third")]
print("Hommes de 3e classe :", hommes["survived"].mean() * 100, "%")

Femmes de 1re classe : 96.80851063829788 %
Hommes de 3e classe : 13.544668587896252 %

In [9]:
titanic["adulte"] = titanic["age"] >= 18

In [10]:
titanic[["age", "adulte"]].head()

    age  adulte
0  22.0    True
1  38.0    True
2  26.0    True
3  35.0    True
4  35.0    True