In [2]:
import pandas as pd

titanic = pd.read_csv("../exercice_08/data/titanic_propre.csv")

titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,Third,man,True,Southampton,no,True

In [3]:
titanic.groupby(["class", "sex"])["survived"].mean().mul(100).round(2)

class   sex
First   female    96.74
        male      38.46
Second  female    91.67
        male      18.48
Third   female    47.24
        male      16.12
Name: survived, dtype: float64

In [4]:
titanic.pivot_table(
    index="class",
    columns="sex",
    values="survived",
    aggfunc="mean"
).mul(100).round(2)

sex     female   male
class
First    96.74  38.46
Second   91.67  18.48
Third    47.24  16.12

les femmes ont mieux survecu que les hommes dans les trois classes (first , second , third ) du Titanic

In [5]:
titanic["tranche_age"] = pd.cut(
    titanic["age"],
    bins=[0, 18, 60, float("inf")],
    labels=["Enfants", "Adultes", "60 ans et plus"],
    right=False
)

titanic.groupby("tranche_age", observed=False)["survived"].mean().mul(100).round(2)

tranche_age
Enfants           54.55
Adultes           39.81
60 ans et plus    28.00
Name: survived, dtype: float64

les enfants ont un taux de survie plus eleve que les adulte et les 60 ans et plus

In [6]:
titanic.groupby("embark_town")["fare"].mean().sort_values(ascending=False).round(2)

embark_town
Cherbourg      64.31
Southampton    29.12
Queenstown     14.68
Name: fare, dtype: float64

In [7]:
pd.crosstab(
    titanic["embark_town"],
    titanic["class"],
    normalize="index"
).mul(100).round(2)

class        First  Second  Third
embark_town
Cherbourg    53.59   11.11  35.29
Queenstown    3.45    5.17  91.38
Southampton  22.24   25.62  52.14

le port Cherbourg presente le prix moyen des billets le plus eleves

In [8]:
titanic.groupby("alone")["survived"].mean().mul(100).round(2)

alone
False    51.04
True     34.17
Name: survived, dtype: float64

In [9]:
titanic.groupby("alone")["survived"].mean().mul(100).round(2).rename(
    index={True: "Voyage seul", False: "Voyage accompagné"}
)

alone
Voyage accompagné    51.04
Voyage seul          34.17
Name: survived, dtype: float64

Les passagers voyageant accompagnés ont un taux de survie plus élevé que les autres.